# Generated by Django 3.2.6 on 2021-11-27 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('timestamp_end', models.DateTimeField(default=datetime.datetime(2021, 12, 4, 16, 22, 10, 801353, tzinfo=utc), verbose_name='Время окончания')),
                ('type', models.CharField(choices=[('Компьютерное моделирование', 'Компьютерное моделирование'), ('Бумажное проектирование', 'Бумажное проектирование')], default='Компьютерное моделирование', max_length=40, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайн',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('position', models.CharField(choices=[('Дизайнер', 'Дизайнер'), ('Мастер', 'Мастер'), ('Водитель', 'Водитель')], default='Дизайнер', max_length=40, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.TextField(max_length=200, verbose_name='Предпочтения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main_app.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('timestamp_end', models.DateTimeField(default=datetime.datetime(2021, 12, 4, 16, 22, 10, 802353, tzinfo=utc), verbose_name='Время окончания')),
                ('design', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production', to='main_app.design', verbose_name='Дизайн')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production', to='main_app.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производство',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('Кровать', 'Кровать'), ('Диван', 'Диван'), ('Кресло', 'Кресло')], default='Кровать', max_length=30, verbose_name='Вид')),
                ('size', models.FloatField(verbose_name='Размер, м3')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('production', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='main_app.production', verbose_name='Производство')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('timestamp_end', models.DateTimeField(default=datetime.datetime(2021, 12, 27, 16, 22, 10, 800348, tzinfo=utc), verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Ожидает подписания договора', 'Ожидает подписания договора'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Стадия дизайана', 'Стадия дизайана'), ('В производстве', 'В производстве'), ('Доставляется', 'Доставляется'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Создан', max_length=40, verbose_name='Статус')),
                ('request', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='main_app.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='design',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to='main_app.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='design',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to='main_app.worker', verbose_name='Работник'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('timestamp_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время конца')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main_app.order', verbose_name='Заказ')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='main_app.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=50, verbose_name='Номера')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='main_app.worker', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость, руб.')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='main_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
