# Generated by Django 3.2.6 on 2021-11-24 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.AddField(
            model_name='design',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design', to='main_app.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='design',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 15, 49, 6, 913392, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 15, 49, 6, 911396, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='production',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 15, 49, 6, 913392, tzinfo=utc), verbose_name='Время окончания'),
        ),
    ]
