# Generated by Django 3.2.6 on 2021-11-29 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 16, 14, 29, 943469, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 16, 14, 29, 942470, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='production',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 16, 14, 29, 943469, tzinfo=utc), verbose_name='Время окончания'),
        ),
    ]
