# Generated by Django 3.2.6 on 2021-11-30 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211129_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='number_of_products',
        ),
        migrations.AlterField(
            model_name='design',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 14, 8, 30, 991512, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 14, 8, 30, 990523, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='production',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 14, 8, 30, 992577, tzinfo=utc), verbose_name='Время окончания'),
        ),
    ]
