# Generated by Django 3.2.6 on 2021-11-30 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211130_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='number_of_products',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='design',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 14, 17, 55, 74684, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 14, 17, 55, 73687, tzinfo=utc), verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='production',
            name='timestamp_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 14, 17, 55, 75684, tzinfo=utc), verbose_name='Время окончания'),
        ),
    ]
